# Generated by Django 3.2.17 on 2023-06-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255)),
                ('text_content', models.TextField()),
                ('audio_content', models.FileField(null=True, upload_to='audio')),
                ('video_content', models.FileField(null=True, upload_to='video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
